In [2]:
import numpy as np

In [3]:
arr = np.arange(0, 11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[1]

1

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
arr = np.arange(0, 11)

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
slice_of_arr = arr[0:5]

In [16]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [18]:
slice_of_arr[:] = 99

In [19]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [20]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [22]:
arr_copy = arr.copy()

In [24]:
arr[:] = 100

In [25]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [26]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [29]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [30]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [34]:
arr_2d.shape # Row and then columns

(3, 3)

In [36]:
arr_2d[0] # The first row

array([ 5, 10, 15])

In [37]:
arr_2d[0, 0] 

5

In [38]:
arr_2d[0][0]

5

In [40]:
arr_2d[:2,1:] # arr_2d[:2][1:]

array([[10, 15],
       [25, 30]])

In [41]:
arr = np.arange(1, 11)

In [42]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [45]:
bool_arr = arr > 4

In [46]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [47]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [49]:
arr[(arr>4)] # We can do this all in one step

array([ 5,  6,  7,  8,  9, 10])