In [1]:
import numpy as np

In [3]:
arr = np.arange(0, 10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
arr/arr

<ipython-input-8-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
1/arr #Numpy gives a warning when dividing by 0

<ipython-input-11-8595183fb9e2>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr #Numpy gives a warning when dividing by 0


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [13]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [14]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr.sum()

45

In [17]:
arr.mean()

4.5

In [18]:
arr.max()

9

In [19]:
arr.min()

0

In [20]:
arr.std()

2.8722813232690143

In [21]:
arr.var()

8.25

In [23]:
arr_2d = np.arange(0, 25).reshape(5, 5)

In [24]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
arr_2d.sum() # Returns the sum of the entire array

300

In [27]:
arr_2d.sum(axis=0) # This performs the sum accross the rows

array([50, 55, 60, 65, 70])

In [30]:
arr_2d.sum(axis=1) # This performs the operations accross the columns

array([ 10,  35,  60,  85, 110])