In [5]:
import numpy as np
li = [1, 2, 3]
type(li)

list

In [4]:
my_list = np.array(li)
type(my_list)

numpy.ndarray

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.linspace(0,40, 3)

array([ 0., 20., 40.])

In [17]:
np.linspace(0, 40)

array([ 0.        ,  0.81632653,  1.63265306,  2.44897959,  3.26530612,
        4.08163265,  4.89795918,  5.71428571,  6.53061224,  7.34693878,
        8.16326531,  8.97959184,  9.79591837, 10.6122449 , 11.42857143,
       12.24489796, 13.06122449, 13.87755102, 14.69387755, 15.51020408,
       16.32653061, 17.14285714, 17.95918367, 18.7755102 , 19.59183673,
       20.40816327, 21.2244898 , 22.04081633, 22.85714286, 23.67346939,
       24.48979592, 25.30612245, 26.12244898, 26.93877551, 27.75510204,
       28.57142857, 29.3877551 , 30.20408163, 31.02040816, 31.83673469,
       32.65306122, 33.46938776, 34.28571429, 35.10204082, 35.91836735,
       36.73469388, 37.55102041, 38.36734694, 39.18367347, 40.        ])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.random.rand(3)

array([0.92331414, 0.33945361, 0.27915623])

In [25]:
np.random.rand(3, 4)

array([[0.0166549 , 0.35111307, 0.20193055, 0.49801107],
       [0.63663935, 0.60636686, 0.98304345, 0.34406561],
       [0.77928868, 0.48974038, 0.39802827, 0.87286291]])

In [36]:
np.random.randn(3, 4)

array([[ 2.19487028,  0.44836505,  0.00938472, -0.43747539],
       [-1.24849437,  0.26110024, -1.04075301, -0.50131313],
       [-0.00429646,  0.8572159 , -0.09580107,  0.13273685]])

In [40]:
np.random.randint(0, 23, (4,5), int)

array([[ 1, 22,  3, 10, 10],
       [19, 16,  3,  3, 14],
       [ 5, 13, 11,  8, 21],
       [15, 22, 19, 18,  1]])

In [41]:
np.random.seed(42) # Get a specfic set of random values, allows to get consistent random values
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [43]:
arr = np.arange(0, 25)

In [44]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [46]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [49]:
ranarr = np.random.randint(0, 101, 10)
ranarr

array([57, 21, 88, 48, 90, 58, 41, 91, 59, 79])

In [50]:
ranarr.max()

91

In [51]:
ranarr.argmax()

7

In [52]:
arr.shape

(25,)

In [53]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])