## Feature Scaling

- Helps to improve the convergence of steepest descent algorithims, want to have the simlar number of iterations for updating weights for each feature. Feature Scaling helps with that
- Helps to increase performance, neeeded for some models
- Two ways to scale the data: 
    - Standarization: data will have a mean of 0 and a standard deviation for (1), normal distrubition
    - Normalization: Scales data to be between 0 and 1

- Scikitlearn has many other scaling methods, and this is done using the fit and transform functions: 
    - fit: calculates the stats needed for scaling (Xmin, Xmax, mean, standard dev)
    - transform: scales the data, and returns the scaled version of the data
- Need to ensure that you only call fit/transform only on the test set, never on the total data


## Cross Validation

- We want to be able to train on all of the data, and also test on all of the data. How do we do this?
- Choose a number K.Split your data on K groups. Set aside 1/K data for testing, and then train on K-1 remaing groups. Get the error. Repeat the process on each group, and then calculate the average error. We have the repeat the process K times. (K- folder cross validation)
- We can also set aside a hold out test set -> never adjust any parameters on this. Nothing is adjusted based on this. 

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("Advertising.csv")

In [4]:
X = df.drop("sales",axis=1)

In [5]:
y = df["sales"]

In [6]:
from sklearn.preprocessing import PolynomialFeatures

In [7]:
poly_converter = PolynomialFeatures(degree=3, include_bias=False, )

In [8]:
poly_features = poly_converter.fit_transform(X)

In [9]:
poly_features.shape

(200, 19)

In [40]:
from sklearn.model_selection import train_test_split
#help(train_test_split)

In [32]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [33]:
X_train.shape

(140, 19)

In [34]:
from sklearn.preprocessing import StandardScaler

In [35]:
scaler = StandardScaler()

In [36]:
scaler.fit(X_train)

StandardScaler()

In [37]:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [39]:
X_train

array([[ 0.49300171, -0.33994238,  1.61586707, ..., -0.16360242,
         0.54694754,  1.37075536],
       [ 1.61337153,  1.32852213,  1.90079242, ...,  2.63236858,
         2.6297449 ,  1.95593378],
       [-0.84811893, -1.58789957, -1.02319564, ..., -0.72634944,
        -0.61593941, -0.54133745],
       ...,
       [ 1.04606563, -1.30982215,  0.27064572, ..., -0.71065643,
        -0.53420112, -0.20690952],
       [ 0.74817069,  0.03987068, -1.26608283, ..., -0.66805936,
        -0.61031703, -0.54616941],
       [ 0.13813882,  0.55533126,  1.01799092, ...,  0.61006767,
         0.67881488,  0.45425942]])

### Ridge Regression

In [41]:
from sklearn.linear_model import Ridge

In [42]:
help(Ridge)

Help on class Ridge in module sklearn.linear_model._ridge:

class Ridge(sklearn.base.MultiOutputMixin, sklearn.base.RegressorMixin, _BaseRidge)
 |  Ridge(alpha=1.0, *, fit_intercept=True, normalize=False, copy_X=True, max_iter=None, tol=0.001, solver='auto', random_state=None)
 |  
 |  Linear least squares with l2 regularization.
 |  
 |  Minimizes the objective function::
 |  
 |  ||y - Xw||^2_2 + alpha * ||w||^2_2
 |  
 |  This model solves a regression model where the loss function is
 |  the linear least squares function and regularization is given by
 |  the l2-norm. Also known as Ridge Regression or Tikhonov regularization.
 |  This estimator has built-in support for multi-variate regression
 |  (i.e., when y is a 2d-array of shape (n_samples, n_targets)).
 |  
 |  Read more in the :ref:`User Guide <ridge_regression>`.
 |  
 |  Parameters
 |  ----------
 |  alpha : {float, ndarray of shape (n_targets,)}, default=1.0
 |      Regularization strength; must be a positive float. Regul

In [43]:
ridge_model = Ridge(alpha=10)

In [44]:
ridge_model.fit(X_train, y_train)

Ridge(alpha=10)

In [45]:
test_pred = ridge_model.predict(X_test)

In [46]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [47]:
MAE = mean_absolute_error(test_pred, y_test)
MAE

0.5774404204714183

In [49]:
MSE = mean_squared_error(test_pred, y_test)
MSE

0.8003783071528416

In [51]:
RMSE = np.sqrt(MSE)
RMSE

0.8946386461319685

In [53]:
from sklearn.linear_model import RidgeCV

In [59]:
ridgecv_model = RidgeCV(scoring="neg_root_mean_squared_error")

In [60]:
ridgecv_model.fit(X_train, y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_root_mean_squared_error')

In [61]:
ridgecv_model.alpha_

0.1

In [57]:
#from sklearn.metrics import SCORERS

In [58]:
#SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_weighted'])

In [63]:
test_pred = ridgecv_model.predict(X_test)

In [65]:
MAE = mean_absolute_error(test_pred,y_test)
MAE

0.42737748843352086

In [67]:
RSME = np.sqrt(mean_squared_error(test_pred, y_test))
RSME

0.6180719926924644

In [68]:
ridgecv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

### LASSO - Least absolute shrinkage and selection operator

In [70]:
from sklearn.linear_model import LassoCV

In [71]:
help(LassoCV)

Help on class LassoCV in module sklearn.linear_model._coordinate_descent:

class LassoCV(sklearn.base.RegressorMixin, LinearModelCV)
 |  LassoCV(*, eps=0.001, n_alphas=100, alphas=None, fit_intercept=True, normalize=False, precompute='auto', max_iter=1000, tol=0.0001, copy_X=True, cv=None, verbose=False, n_jobs=None, positive=False, random_state=None, selection='cyclic')
 |  
 |  Lasso linear model with iterative fitting along a regularization path.
 |  
 |  See glossary entry for :term:`cross-validation estimator`.
 |  
 |  The best model is selected by cross-validation.
 |  
 |  The optimization objective for Lasso is::
 |  
 |      (1 / (2 * n_samples)) * ||y - Xw||^2_2 + alpha * ||w||_1
 |  
 |  Read more in the :ref:`User Guide <lasso>`.
 |  
 |  Parameters
 |  ----------
 |  eps : float, default=1e-3
 |      Length of the path. ``eps=1e-3`` means that
 |      ``alpha_min / alpha_max = 1e-3``.
 |  
 |  n_alphas : int, default=100
 |      Number of alphas along the regularization p

In [78]:
lasso_cv_model = LassoCV(eps=0.1,n_alphas=100)

In [80]:
lasso_cv_model.fit(X_train, y_train)

LassoCV(eps=0.1)

In [81]:
lasso_cv_model.alpha_

0.4943070909225828

In [82]:
test_pred = lasso_cv_model.predict(X_test)

In [83]:
MAE = mean_absolute_error(test_pred,y_test)
MAE

0.6541723161252854

In [84]:
RSME = np.sqrt(mean_squared_error(test_pred, y_test))
RSME

1.130800102276253

In [85]:
lasso_cv_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [86]:
X_train

array([[ 0.49300171, -0.33994238,  1.61586707, ..., -0.16360242,
         0.54694754,  1.37075536],
       [ 1.61337153,  1.32852213,  1.90079242, ...,  2.63236858,
         2.6297449 ,  1.95593378],
       [-0.84811893, -1.58789957, -1.02319564, ..., -0.72634944,
        -0.61593941, -0.54133745],
       ...,
       [ 1.04606563, -1.30982215,  0.27064572, ..., -0.71065643,
        -0.53420112, -0.20690952],
       [ 0.74817069,  0.03987068, -1.26608283, ..., -0.66805936,
        -0.61031703, -0.54616941],
       [ 0.13813882,  0.55533126,  1.01799092, ...,  0.61006767,
         0.67881488,  0.45425942]])

In [87]:
from sklearn.linear_model import ElasticNetCV

In [89]:
elastic_model = ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1],eps=0.001,n_alphas=100, max_iter=1000000)

In [90]:
elastic_model.fit(X_test, y_test)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [92]:
elastic_model.l1_ratio_

1.0

In [93]:
test_pred = elastic_model.predict(X_test)

In [94]:
MAE = mean_absolute_error(test_pred,y_test)
MAE

0.39904655462963284

In [95]:
RSME = np.sqrt(mean_squared_error(test_pred, y_test))
RSME

0.5812005863666974